# -*- coding: utf-8 -*-
"""Aula1_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XKvn01B2Vq1JKy3vgTk8eTF3rs4ZW-dG
"""



"""### Python para analise de dados"""

#importando a biblioteca pandas
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/datasets/Gapminder.csv", error_bad_lines=False, sep=";")

#Visalizando as 10 primeiras linhas
df.head(10)

#trocando o nome das colunas
df = df.rename(columns={"country":"Pais", "continent": "continente", "year":"ano", "lifeExp":"Expectativa de vida", "pop":"Pop Total", "gdpPercap":"PIB"})

#para saber o numero de linhas e colunas no nosso conjunto de dados
df.shape

#para retornar as colunas
df.columns

#tipo de dados em cada coluna
df.dtypes

#para mostrar as ultimas linhas
df.tail(15)

#para retornar informacoes estatisticas sobre o conjunto de dados
df.describe()

#para mostrar as informacoes de uma coluna
df["continente"].unique()

#Para retornar apenas os valores do continente Oceania
Oceania = df.loc[df["continente"] == "Oceania"]
Oceania.head()

Oceania["continente"].unique()

#Para fazer group by
df.groupby("continente")["Pais"].nunique()

#Para saber a expectativa de vida media, para cada ano
df.groupby("ano")["Expectativa de vida"].mean()

#media
df['PIB'].mean()

#soma
df['PIB'].sum()

