# -*- coding: utf-8 -*-
"""Estrutura de dados (listas, tuplas e dicionarios).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oH9Ev__x6PydBTZgaOlNVmc8tirPymn8

Listas
"""

#Criando uma lista chamada animais
animais = [1,2,3]
animais

animais = ["cachorro", "gato", 12345, 6.5]
animais

#Imprimindo o primeiro elemento da lista
animais[0]

#Imprimindo o 4 elemento da lista
animais[3]

#Substituindo o primeiro elemento da lista
animais[0] = "papagaio"

animais

#Removendo gato da lista
animais.remove("gato")

animais

#Para saber o tamanho da lista (o numero de elementos)
len(animais)

#Para saber se um elemento esta na lista
"gato" in animais

lista = [500, 30, 300, 80, 10]

#Para saber o maior elemento da lista
max(lista)

#Para saber o menor elemento da lista
min(lista)

#Para adicionar 1 elemento a lista
animais.append("leao")

animais

#Para adicionar mais de um elemento a lista
animais.extend(["cobra", 6])

animais

#Para ver quantas vezes aparece um elemento na lista
animais.count("leao")

#Ordenar a lista do menor para o maior
lista.sort()

lista

"""Tuplas"""

#As tuplas usam parenteses como sintaxe
tp = ("Banana", "Maca", 10, 50)

#Retornando o primeiro elemento
tp[0]

#Diferente das listas as tuplas sao imutaveis, o que quer dizer que nao podemos alterar os seus elementos
tp[0] = "Laranja"

#para contar quantas vezes um elemento aparece na tupla
tp.count("Maca")

#quando eu quero pegar do indice 0 ao 1 (lembrar que o ultimo e excludente)
tp[0:2]

"""Dicionario"""

#Para criar um dicionario utilizamos as {}
dc = {"Maca":20, "Banana":10, "Laranja":15, "Uva":5} #Dicionarios trabalham com o condeito chave e valor

dc

#Acessando o valor de um dicionario atraves da chave
dc["Maca"]

#Atualizando o valor de maca
dc["Maca"] = 25
dc

#Retornando todas as chaves de um dicionario
dc.keys()

#Retornando valores do dicionario
dc.values()

#Verificando se ja existe uma chave no dicionario e caso nao exista inserir
dc.setdefault("Limao", 22)
dc

